import type { Metadata } from "next";
import "./globals.css";

// For Layout Components
import Navbar from "@/app/Layout/Navbar/Navbar";


export const metadata: Metadata = {
  title: "Netflix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
